/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistemaos.telas;

import br.com.sistemaos.dao.ModuloConexao;
import java.sql.Connection;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class TelaMenu extends javax.swing.JInternalFrame {
    Connection conexao = null;
    
    public TelaMenu() {
        initComponents();
        conexao = ModuloConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOS = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnRelatorios = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Menu do Sistema");
        getContentPane().setLayout(null);

        btnOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistemaos/icones/btn_os.png"))); // NOI18N
        btnOS.setToolTipText("Ordem de Serviço");
        btnOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOSActionPerformed(evt);
            }
        });
        getContentPane().add(btnOS);
        btnOS.setBounds(50, 20, 80, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistemaos/icones/os.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(77, 115, 541, 294);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistemaos/icones/btn_sair.png"))); // NOI18N
        btnSair.setToolTipText("Sair");
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(600, 20, 80, 70);

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistemaos/icones/btn_buscar.png"))); // NOI18N
        btnPesquisar.setToolTipText("Pesquisar");
        btnPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar);
        btnPesquisar.setBounds(490, 20, 80, 70);

        btnRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistemaos/icones/btn_relatorios.jpg"))); // NOI18N
        btnRelatorios.setToolTipText("Relatórios");
        btnRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatoriosActionPerformed(evt);
            }
        });
        getContentPane().add(btnRelatorios);
        btnRelatorios.setBounds(400, 20, 70, 70);

        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistemaos/icones/btn_users.png"))); // NOI18N
        btnUsuarios.setToolTipText("Usuários");
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.setEnabled(false);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsuarios);
        btnUsuarios.setBounds(290, 20, 70, 70);

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistemaos/icones/btn_clientes.png"))); // NOI18N
        btnClientes.setToolTipText("Clientes");
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnClientes);
        btnClientes.setBounds(160, 20, 80, 70);

        setBounds(0, 0, 704, 449);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOSActionPerformed
        TelaOS oS = new TelaOS();
        TelaPrincipal.desktop.add(oS);
        oS.setVisible(true);
    }//GEN-LAST:event_btnOSActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        TelaOS oS = new TelaOS();
        TelaPrincipal.desktop.add(oS);
        oS.setVisible(true);
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosActionPerformed
        int confirma = JOptionPane.showConfirmDialog(null, "Deseja realmente viusalizar o relatório?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            try {
                JasperPrint print = JasperFillManager.fillReport("/home/joao/Vídeos/JavaMySql + SistemaOS/SistemaOS/src/MyReports/servico.jasper", null, conexao); // pega o relatorio
                JasperViewer.viewReport(print, false);//abre em modo de visualização
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERRO: " + e.getMessage());
            }
            
        }
    }//GEN-LAST:event_btnRelatoriosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        TelaUsuario usuario = new TelaUsuario();
        TelaPrincipal.desktop.add(usuario);
        usuario.setVisible(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        TelaCliente cliente = new TelaCliente();
        TelaPrincipal.desktop.add(cliente);
        cliente.setVisible(true);
    }//GEN-LAST:event_btnClientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnOS;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnRelatorios;
    private javax.swing.JButton btnSair;
    public static javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
